version: '3.4'
services:
    postgresql:
        image: bn-postgresql
        container_name: bn-postgresql
        build:
            context: ..
            dockerfile: .docker/db/Dockerfile
        env_file:
            - ../api/.env
        volumes:
            - ./db/tmp:/var/lib/postgresql/data
    api-node:
        image: bn-api-node
        container_name: bn-api-node
        build:
            context: ..
            dockerfile: .docker/api/node.Dockerfile
        links:
            - postgresql
    api-nginx:
        image: bn-api-nginx
        container_name: bn-api-nginx
        build:
            context: ..
            dockerfile: .docker/api/nginx.Dockerfile
        ports:
            - 8080:8080
        links:
            - api-node
    www:
        image: bn-www
        container_name: bn-www
        build:
            context: ..
            dockerfile: .docker/www/Dockerfile
        ports:
            - 80:8080
