version: "3"
services:
    postgresql:
        image: "postgres:11-alpine"
        container_name: bn-postgresql
        environment:
            POSTGRES_DB: bn
            POSTGRES_USER: bn
            POSTGRES_PASSWORD: 5Kn317rj1RJrVDaV
    nginx:
        image: "nginx:1-alpine"
        container_name: bn-nginx
        volumes:
            - ./bn.nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - node
        ports:
            - "8000:80"
    node:
        image: bn-node
        container_name: bn-node
        build:
            context: ..
            dockerfile: .docker/node.dockerfile
        volumes:
            - ..:/opt/bn
        links:
            - postgresql
