version: '3.4'
services:
    api-node:
        build:
            target: dev
        volumes:
            - ../api:/opt/bn
            - /opt/bn/node_modules/
        command: "sh -c 'npm install && npm run start:dev'"
    www:
        build:
            target: dev
        volumes:
            - ../www:/opt/bn
            - /opt/bn/node_modules/
        command: "sh -c 'npm install && npm run serve'"
