version: "3"
services:
    postgresql:
        image: postgres:11-alpine
        container_name: bn-postgresql
        environment:
            POSTGRES_DB: bn
            POSTGRES_USER: bn
            POSTGRES_PASSWORD: 5Kn317rj1RJrVDaV
    api-node:
        image: bn-api-node
        container_name: bn-api-node
        build:
            context: ../api
            dockerfile: ../.docker/api/Dockerfile
        volumes:
            - ../api:/opt/bn
            - /opt/bn/node_modules/
        links:
            - postgresql
        command: npm run start:dev
    api-nginx:
        image: nginx:1-alpine
        container_name: bn-api-nginx
        volumes:
            - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - api-node
        ports:
            - 8080:80
    www:
        image: bn-www
        container_name: bn-www
        build:
            context: ../www
            dockerfile: ../.docker/www/Dockerfile
        volumes:
            - ./www/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../www:/opt/bn
            - /opt/bn/node_modules/
        ports:
            - 80:8080
        command: npm run serve
